[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log

[program:leaky-app]
command=java -Xmx128m -Xms64m -cp /app/demo/leaky-app LeakyApp 8091
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:cpu-hog]
command=java -Xmx128m -Xms64m -cp /app/demo/cpu-hog CpuHogApp 8092
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:thread-contention]
command=java -Xmx128m -Xms64m -cp /app/demo/thread-contention ThreadContentionApp 8093
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:gc-pressure]
command=java -Xmx128m -Xms64m -cp /app/demo/gc-pressure GcPressureApp 8094
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:hub]
command=java -Xmx512m -Dserver.port=%(ENV_PORT)s -jar /app/hub.jar
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
